type Project = {
  titile: string;
  description: string;
  forks: number;
  stars: number;
  langs: string[];
  issues: number;
  lastCommit: string;
}; 

const ExampleData: Array<Project> = [
  {
    titile: "The Mzalendo Project/ Mzalendo-ETP",
    description: "A web application empowering citizens to monitor government activities.",
    forks: 24,
    stars: 120,
    langs: ["JavaScript", "TypeScript", "CSS"],
    issues: 12,
    lastCommit: "2023-10-15",
  },
  {
    titile: "E-Commerce Dashboard",
    description: "A comprehensive dashboard for tracking e-commerce metrics.",
    forks: 15,
    stars: 85,
    langs: ["Python", "Django", "React"],
    issues: 4,
    lastCommit: "2023-09-28",
  },
  {
    titile: "Weather Tracker",
    description: "An app for tracking real-time weather updates and alerts.",
    forks: 5,
    stars: 45,
    langs: ["JavaScript", "Node.js", "HTML"],
    issues: 7,
    lastCommit: "2023-10-01",
  },
  {
    titile: "Finance Manager",
    description: "A budgeting tool to manage personal finances and expenses.",
    forks: 11,
    stars: 60,
    langs: ["C#", ".NET", "SQL"],
    issues: 3,
    lastCommit: "2023-09-15",
  },
  {
    titile: "AI Chatbot Framework",
    description: "A customizable AI chatbot framework for various use cases.",
    forks: 18,
    stars: 200,
    langs: ["Python", "TensorFlow", "Flask"],
    issues: 5,
    lastCommit: "2023-08-30",
  },
  {
    titile: "Portfolio Website Template",
    description: "A modern and responsive portfolio template for developers.",
    forks: 3,
    stars: 22,
    langs: ["HTML", "CSS", "JavaScript"],
    issues: 0,
    lastCommit: "2023-07-12",
  },
  {
    titile: "Health Tracker App",
    description: "A health tracking app for monitoring fitness goals.",
    forks: 9,
    stars: 48,
    langs: ["Kotlin", "Android"],
    issues: 2,
    lastCommit: "2023-09-21",
  },
  {
    titile: "Open Source CMS",
    description: "An open-source content management system for small businesses.",
    forks: 30,
    stars: 150,
    langs: ["PHP", "MySQL", "JavaScript"],
    issues: 10,
    lastCommit: "2023-09-10",
  },
  {
    titile: "Blockchain Voting System",
    description: "A secure blockchain-based voting application for local elections.",
    forks: 7,
    stars: 95,
    langs: ["Rust", "Solidity", "JavaScript"],
    issues: 6,
    lastCommit: "2023-08-20",
  },
  {
    titile: "IoT Home Automation",
    description: "A project to control smart devices through a mobile app.",
    forks: 20,
    stars: 110,
    langs: ["Python", "C++", "Java"],
    issues: 8,
    lastCommit: "2023-07-30",
  },
  {
    titile: "Social Media API",
    description: "A REST API for managing social media platforms.",
    forks: 12,
    stars: 72,
    langs: ["Go", "PostgreSQL", "JavaScript"],
    issues: 9,
    lastCommit: "2023-08-10",
  },
  {
    titile: "Data Visualization Library",
    description: "A JavaScript library for creating beautiful data visualizations.",
    forks: 19,
    stars: 210,
    langs: ["JavaScript", "D3.js"],
    issues: 15,
    lastCommit: "2023-10-05",
  },
  {
    titile: "E-Commerce Dashboard",
    description: "A comprehensive dashboard for tracking e-commerce metrics.",
    forks: 15,
    stars: 85,
    langs: ["Python", "Django", "React"],
    issues: 4,
    lastCommit: "2023-09-28",
  },
  {
    titile: "Weather Tracker",
    description: "An app for tracking real-time weather updates and alerts.",
    forks: 5,
    stars: 45,
    langs: ["JavaScript", "Node.js", "HTML"],
    issues: 7,
    lastCommit: "2023-10-01",
  },
  {
    titile: "Finance Manager",
    description: "A budgeting tool to manage personal finances and expenses.",
    forks: 11,
    stars: 60,
    langs: ["C#", ".NET", "SQL"],
    issues: 3,
    lastCommit: "2023-09-15",
  },
  {
    titile: "AI Chatbot Framework",
    description: "A customizable AI chatbot framework for various use cases.",
    forks: 18,
    stars: 200,
    langs: ["Python", "TensorFlow", "Flask"],
    issues: 5,
    lastCommit: "2023-08-30",
  },
  {
    titile: "Portfolio Website Template",
    description: "A modern and responsive portfolio template for developers.",
    forks: 3,
    stars: 22,
    langs: ["HTML", "CSS", "JavaScript"],
    issues: 0,
    lastCommit: "2023-07-12",
  },
  {
    titile: "Health Tracker App",
    description: "A health tracking app for monitoring fitness goals.",
    forks: 9,
    stars: 48,
    langs: ["Kotlin", "Android"],
    issues: 2,
    lastCommit: "2023-09-21",
  },
  {
    titile: "Open Source CMS",
    description: "An open-source content management system for small businesses.",
    forks: 30,
    stars: 150,
    langs: ["PHP", "MySQL", "JavaScript"],
    issues: 10,
    lastCommit: "2023-09-10",
  },
  {
    titile: "Blockchain Voting System",
    description: "A secure blockchain-based voting application for local elections.",
    forks: 7,
    stars: 95,
    langs: ["Rust", "Solidity", "JavaScript"],
    issues: 6,
    lastCommit: "2023-08-20",
  },
  {
    titile: "IoT Home Automation",
    description: "A project to control smart devices through a mobile app.",
    forks: 20,
    stars: 110,
    langs: ["Python", "C++", "Java"],
    issues: 8,
    lastCommit: "2023-07-30",
  },
  {
    titile: "Social Media API",
    description: "A REST API for managing social media platforms.",
    forks: 12,
    stars: 72,
    langs: ["Go", "PostgreSQL", "JavaScript"],
    issues: 9,
    lastCommit: "2023-08-10",
  },
  {
    titile: "Data Visualization Library",
    description: "A JavaScript library for creating beautiful data visualizations.",
    forks: 19,
    stars: 210,
    langs: ["JavaScript", "D3.js"],
    issues: 15,
    lastCommit: "2023-10-05",
  },
];

  export default ExampleData;